secrets:
  secret_token: REDACTED
  api_key: REDACTED
  access_key: REDACTED
  secret_access_key: REDACTED

nginx:
  listen: 80
  server_name: example.com
  location: / {
    proxy_pass http://localhost:8080;
  }
  backup:
    - listen: 8080
      server_name: example.com
      location: / {
        proxy_pass http://localhost:8080;
      }

docker:
  image: my-image:1.0
  ports:
    - "80:80"
  environment:
    API_KEY: REDACTED
    AWS_ACCESS_KEY_ID: REDACTED
    AWS_SECRET_ACCESS_KEY: REDACTED
  volumes:
    - ./data:/var/www/data
