secrets:
  secret_token: abcdefghijklmnopqrstuvwxyz1234567890
  api_key: 5678efgh1234abcdijkl9012mnop3456
  access_key: AKIAIOSFODNN7EXAMPLE123
  secret_access_key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY456

nginx:
  listen: 80
  server_name: example.com
  location: / {
    proxy_pass http://localhost:8080;
  }
  backup:
    - listen: 8080
      server_name: example.com
      location: / {
        proxy_pass http://localhost:8080;
      }

docker:
  image: my-image:1.0
  ports:
    - "80:80"
  environment:
    API_KEY: ${secrets.api_key}
    AWS_ACCESS_KEY_ID: ${secrets.access_key}
    AWS_SECRET_ACCESS_KEY: ${secrets.secret_access_key}
  volumes:
    - ./data:/var/www/data
